version: '3'
services:
 bitbucket:
  image: "atlassian/bitbucket-server:6.6.2-ubuntu"
  container_name: bitbucket
  restart: always
  ports:
   - "7990:7990"
   - "7999:7999"
  environment:
   - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
  volumes:
   - bitbucketData:/var/atlassian/application-data/bitbucket
 bitbucket-postgres:
  image: postgres:9.6.15
  container_name: bitbucket-db
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: Pgdock3r
   POSTGRES_USER: genadmin
   POSTGRES_DB: postgres
   PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
   - bitbucketDbVolume:/var/lib/postgresql/data
volumes:
 bitbucketData:
  external:
   name: bitbucketData
 bitbucketDbVolume:
  external:
   name: bitbucketDbVolume
